# Nome da aplicação
spring.application.name=gestao_vagas

# Configurações do banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/gestao_vagas
spring.datasource.username=admin
spring.datasource.password=admin

# Driver do banco de dados
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações adicionais (opcional)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
